[[section-experience]]
== EXPERIENCE
:page-interpolate: true

ifdef::env-vscode[]
include::./env.adoc[]
include::../../env.adoc[]
include::../../config.adoc[]
endif::[]

=== Nobo Automotive (August 2021 ~ present)
[horizontal,role="experience"]
Title:: Software Architect Specialist
Responsibilities::
* Work with cross-functional team for software development, identify risks and drive the execution of planned requirement by creating, documenting and maintaining product software architecture for both application and basic software level.
* Develop and maintain traceability between software requirements, architectural design, interfaces requirements and integration tests as per software development milestones.
* Work with software team members and quality assurance to ensure software work products and deliverables for requirements, software architecture and test methods are in compliance with ISO-26262 guidelines to meet required ASIL levels and ASPICE process.
* Establish strategy for the evolution of a multi-generation/reusable platform software product, product agnostics and highly configurable building blocks for various applications.
* Support RFI efforts by working with direct and indirect suppliers in developing and reviewing requirements, sourcing package and scope of project. Ensure desired functional acceptance criteria meets required standards.
* Act as a liaison and technical leader for vehicle level component and sub-component software architecture deliverables, software verification tools at integration level and tests for both in-house development and software suppliers.
* Mentor and coach team members. Ensure projects are delivered on-time within architecture defined scope.

==== Key Projects
[horizontal,role="experience"]
Project:: V4 Platform (2022-present)
Role:: Software/System Architect
Summary:: Next generation Smart Cockpit Controller Platform, based on SA8295P
Responsibilities::
* From the aspect of ASPICE
** Participate in SYS.1/SYS.2/SYS.3/SWE.1/SWE.2/SWE.3/SWE.5/SWE.6 etc.
** Lead SWE.1/SWE.2/SWE.3
Responsibilities::
* From the aspect of ISO-26262
** Lead the whole 6.Software Level development processes
Tech Stack:: UML/C/C++/AUTOSAR/QNX/Android etc.

Project:: RPAS (2022-present)
Role:: Software Architect
Summary:: BXW Assessment for Tier 1
Responsibilities::
* From the aspect of ASPICE
** Participate in SYS.1/SYS.2/SYS.3/SWE.1/SWE.2/SWE.3/SWE.5/SWE.6 etc.
** Lead SWE.1/SWE.2/SWE.3
Responsibilities::
* From the aspect of ISO-26262
** Lead the whole 6.Software Level development processes
Tech Stack:: UML/EA/Draw.io/ELM/ASCIIDOC/PlantUML etc.

Project:: EC31 (2021-present)
Role:: Software Architect
Summary:: Smart Cockpit Controller for personal Electric SUV, based on SA8155P
Responsibilities::
* From the aspect of ASPICE
** Participate in SYS.1/SYS.2/SYS.3/SWE.1/SWE.2/SWE.3/SWE.5/SWE.6 etc.
** Lead SWE.1/SWE.2/SWE.3
Responsibilities::
* From the aspect of ISO-26262
** Lead the whole 6.Software Level development processes
Tech Stack:: UML/C/C++/AUTOSAR/QNX/Android etc.

Project:: ASPICE Certification (EC31) (2021-2023)
Role:: Software Architect
Summary:: Project Certified by ASPICE CL3
Responsibilities::
* From the aspect of ASPICE
** Participate in SYS.1/SYS.2/SYS.3/SWE.1/SWE.2/SWE.3/SWE.5/SWE.6 etc.
** Lead SWE.1/SWE.2/SWE.3
Tech Stack:: UML/EA/Draw.io/ELM/ASCIIDOC/PlantUML etc.

Project:: HT01 (2022-present)
Role:: Software Architect
Summary:: Smart Cockpit Controller for Business Electric Truck, based on SA8155P
Responsibilities::
* From the aspect of ASPICE
** Participate in SYS.1/SYS.2/SYS.3/SWE.1/SWE.2/SWE.3/SWE.5/SWE.6 etc.
** Lead SWE.1/SWE.2/SWE.3
Responsibilities::
* From the aspect of ISO-26262
** Lead the whole 6.Software Level development processes
Tech Stack:: UML/C/C++/AUTOSAR/QNX/Android etc.

Project:: B16ovs & B07ovs (2022-present)
Role:: Software Architect
Summary:: Smart Cockpit Controller for personal Hybrid SUV(focused on oversea market), based on SA8155P
Responsibilities::
* From the aspect of ASPICE
** Participate in SYS.1/SYS.2/SYS.3/SWE.1/SWE.2/SWE.3/SWE.5/SWE.6 etc.
** Lead SWE.1/SWE.2/SWE.3
Responsibilities::
* From the aspect of ISO-26262
** Lead the whole 6.Software Level development processes
Tech Stack:: UML/C/C++/AUTOSAR/QNX/Android etc.

Project:: P01ovs (2021-present)
Role:: Software Architect
Summary:: Smart Cockpit Controller for personal Hybrid SUV(focused on oversea market), based on SA8155P
Responsibilities::
* From the aspect of ASPICE
** Participate in SYS.1/SYS.2/SYS.3/SWE.1/SWE.2/SWE.3/SWE.5/SWE.6 etc.
** Lead SWE.1/SWE.2/SWE.3
Responsibilities::
* From the aspect of ISO-26262
** Lead the whole 6.Software Level development processes
Tech Stack:: UML/C/C++/AUTOSAR/QNX/Android etc.

Project:: P05 (2021-2022)
Role:: Software Architect
Summary:: Smart Cockpit Controller for petrol pickup trunk, based on SA8155P
Responsibilities::
* From the aspect of ASPICE
** Participate in SYS.1/SYS.2/SYS.3/SWE.1/SWE.2/SWE.3/SWE.5/SWE.6 etc.
** Lead SWE.1/SWE.2/SWE.3
Responsibilities::
* From the aspect of ISO-26262
** Lead the whole 6.Software Level development processes
Tech Stack:: UML/C/C++/AUTOSAR/QNX/Android etc.

Project:: DE07 (2021-2022 canceled)
Role:: Software Architect
Summary:: Smart Cockpit Controller for personal Hybrid SUV (GWM's Next generation E/E Architecture), based on SA8155P
Responsibilities::
* From the aspect of ASPICE
** Participate in SYS.1/SYS.2/SYS.3/SWE.1/SWE.2/SWE.3/SWE.5/SWE.6 etc.
** Lead SWE.1/SWE.2/SWE.3
Responsibilities::
* From the aspect of ISO-26262
** Lead the whole 6.Software Level development processes
Tech Stack:: UML/C/C++/AUTOSAR/QNX/Android etc.

=== CYG Intelligent Automation (April 2021 ~ August 2021)
[horizontal,role="experience"]
Title:: Lead Software Architect/Principal Software Engineer
Responsibilities::
* Supervised and lead a team of 8 junior/senior software engineers
* Designing, coding, and debugging Test Master System
* Providing training and mentor other Engineers
* Gathering early non-functional/functional requirements
* Evaluating functional requirements captured by a business analyst
* Interact with clients, product managers, and developers to envision, model, and design the system/software solution
* Selecting a technology stack and deployment methods
* Estimating development time
* Designing a high-level architectural solution
* Work with other Engineers in planning, prioritizing and executing assigned
tasks within deadlines.
Reason for Leaving:: Company restructuring

==== Key Projects
[horizontal,role="experience"]
Project:: Test Master System (2021)
Role:: Lead Software Architect/Principal Software Engineer
Responsibilities::
* Requirement analysis/ System/Software Design/Coding
* Project/Team management
Tech Stack:: UML/C++/Python/Lua/gRPC/MQTT/QT/PostgreSQL/MongoDB/macOS/Linux/Windows 

Project:: Vision-based Testing System (2021)
Role:: Lead Software Architect/Principal Software Engineer
Responsibilities::
* Requirement analysis/ System/Software Design/Coding/HW selection
* Project/Team management
Tech Stack:: C++/Python/MQTT/QT/ADLINK Motion SDK/MongoDB/macOS/Windows etc

=== 2021 VeEX Inc. (April 2012 ~ April)
[horizontal,role="experience"]
Title:: Software Development Manager/Lead Software Architect
Responsibilities::
* Supervised and lead a team of 20+ junior/senior software engineers
* Designing, coding, and debugging both Server and Embedded devices
* Providing training and mentor other Engineers
* Recommend new technologies to ensure quality and productivity
* Responsible for the overall planning, execution and success of complex
technical projects
* Work closely with the global marketing team to ensure building the best
possible products.
Reason for Leaving:: Sales fell steeply in US because of COVID-19, the telecom industry is falling

==== Key Projects
[horizontal,role="experience"]
Projects:: 
[none]
* Dozens of Ethernet/Transmission/CATV measurement instruments System/Software Design (2012 ~ 2021)
Role:: 
[none]
* Software Development Manager/Lead Software Architect/Full Stack Engineer
Summary:: Various embedded test meters' System/Software Design/Implementation
Responsibilities:: 
* Requirement analysis/ System/Software Design/Coding
* Project/Team management
Tech Stack:: C++/C/QT/SQLite/MQTT/RPC/Linux/LXC/LXD/Alpine etc.

Projects:: EZ Remote Cloud Service System (Feb. 2020 ~ April 2021)
Summary:: The EZ Remote functionality allows users to quickly and securely connect
to VeEX test sets around the world
Role:: Software Development Manager/Lead Software Architect/Full Stack Engineer
Responsibilities:: 
* Requirement analysis/ System/Software Design/Coding
* Project/Team management
Tech Stack::
C++/Java/TypeScript/JS/Guice/RESTfull/MyBatis/QT/OAuth2/Rocket.chat/Nginx/OpenVPN/K
eycloak/PostgreSQL/MongoDB/Docker/K8S/istio/Centos etc.

Projects:: VeExpress Cloud License Management Service(June 2014 ~ April 2021)
Summary:: VeExpress (US Patent 9,900,393) is a centralized (cloud) service hosted
by VeEX, which allows its customers to seamlessly manage the software licenses
for their geographically-dispersed fleet of test equipment and users
Role:: Software Development Manager/Lead Software Architect
Responsibilities:: 
* Requirement analysis/ System/Software Design/Coding
* Project/Team management
Tech Stack::
C++/C#/JavaScript/AngularJS/.NET/QT/RESTfull/EF/MySQL/Swagger/Windows/Linux/Andro
id/macOS

Projects:: SCPI-based Automation Testing Manager (April 2012 ~ April 2021)
Summary:: To manage, test with VeEX’s test meters in SCPI
Role:: Software Development Manager/Lead Software Architect/Full Stack Engineer
Responsibilities:: 
* Requirement analysis/ System/Software Design/Coding
* Project/Team management
Tech Stack:: C++/C/QT/Linux/Windows/Android/macOS etc.

Projects:: Ethernet Performance Analyzer (Nov.2020 ~ April 2021)
Summary:: Based on Docker + Intel DPDK. An Ethernet performance analyze system.
Role:: Lead Software Architect/Full Stack Engineer
Responsibilities:: 
* Requirement analysis/ System/Software Design/Coding
Tech Stack:: C++/DPDK/QT/PcapPlusPlus/Docker/Centos etc.

=== HUAWEI (Sept. 2007 ~ April 2012)
Title:: Team Leader
Responsibilities::
* Supervised and lead a team of 8 junior/senior software engineers
* Designing, coding, and debugging W-CDMA Base Stations' Embedded devices
* Work closely with the Product Management team to ensure building the best
possible products.
* Experienced with sound debugging techniques, expert in analyzing and
solving the software problem.
* Worked in Italy with Vodafone for 6 months in 2010.
* In charge of the CPU Selection for the next generation of the BBU.
* In charge of the CI/CD
* Experienced in all project phases using Waterfall and Agile Methodologies
Reason for Leaving:: Relocation

==== Key Projects
[horizontal,role="experience"]
Projects:: Dozens of W-CDMA Base Station projects(Sept. 2007 ~ April 2012)
Role:: Software Architect/Senior Software Engineer
Summary:: Design/Maintain the infrastructure & middleware modules
Responsibilities:: 
* Requirement analysis/ System/Software Design/Coding
* Project/Team management
Tech Stack:: C/VxWorks/Linux etc.

Projects:: Multi-core CPU Selection & Validation & Porting (June 2009 ~ April 2012)
Role:: Team Leader
Summary:: Porting source code from ARM+DSP to the multi-core & FPGA platforms
Responsibilities:: 
* Requirement analysis/ System Design/Coding
* Agile Software Development Managing
Tech Stack:: C/VxWorks/Linux etc.

=== Optel Inc. (Sept. 2006 ~ Aug. 2007)
Title:: Senior Software Engineer
Responsibilities::
* Assist the Development Manager with all aspects of software design and
coding
* Coding & Debugging
* Monitoring the technical performance of internal systems
Reason for Leaving:: Better Opportunity 

==== Key Projects
[horizontal,role="experience"]
Projects:: Dozens of Transmission Meters Software Design(Sept. 2006 ~ Aug. 2007)
Role:: Software Engineer/Senior Software Engineer
Summary:: Various embedded test meters' Software Design/Coding
Responsibilities:: 
* Module Requirement analysis/Design/Coding/Debugging
Tech Stack:: C/VxWorks/Linux etc.

